(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AnyDBM_File" "App::Cpan" "App::Prove" "App::Prove::State"
"App::Prove::State::Result" "App::Prove::State::Result::Test"
"Archive::Tar" "Archive::Tar::Constant" "Archive::Tar::File"
"Attribute::Handlers" "Authen::SASL" "Authen::SASL::CRAM_MD5"
"Authen::SASL::EXTERNAL" "Authen::SASL::Perl"
"Authen::SASL::Perl::ANONYMOUS" "Authen::SASL::Perl::CRAM_MD5"
"Authen::SASL::Perl::DIGEST_MD5" "Authen::SASL::Perl::EXTERNAL"
"Authen::SASL::Perl::GSSAPI" "Authen::SASL::Perl::LOGIN"
"Authen::SASL::Perl::PLAIN" "AutoLoader" "AutoSplit" "B" "B::BUtils"
"B::Concise" "B::Debug" "B::Deparse" "B::Lint" "B::Lint::Debug"
"B::Module::Info" "B::Showlex" "B::Terse" "B::Xref" "BSD::Resource"
"Benchmark" "Bit::Vector" "Bit::Vector::Overload" "Bit::Vector::String"
"Bundle::DBD::mysql" "Bundle::DBI" "Bundle::LWP" "Bundle::Net::LDAP" "CORE"
"CPAN" "CPAN::API::HOWTO" "CPAN::Author" "CPAN::Bundle" "CPAN::CacheMgr"
"CPAN::Complete" "CPAN::Config" "CPAN::Debug" "CPAN::DeferredCode"
"CPAN::Distribution" "CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::FTP" "CPAN::FTP::netrc"
"CPAN::FirstTime" "CPAN::HandleConfig" "CPAN::Index" "CPAN::InfoObj"
"CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Mirrors" "CPAN::Module"
"CPAN::Nox" "CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip"
"CPAN::URL" "CPAN::Version" "Cairo" "Cairo::Install::Files" "Carp"
"Carp::Clan" "Carp::Heavy" "ClamTk::App" "ClamTk::Device" "ClamTk::GUI"
"ClamTk::Prefs" "ClamTk::Results" "ClamTk::Schedule" "ClamTk::Submit"
"ClamTk::Update" "Class::Struct" "Clone" "Compress::Raw::Bzip2"
"Compress::Raw::Zlib" "Compress::Zlib" "Config" "Config::Extensions"
"Convert::ASN1" "Convert::ASN1::Debug" "Convert::ASN1::IO"
"Convert::ASN1::_decode" "Convert::ASN1::_encode" "Convert::ASN1::parser"
"Crypt::DES" "Crypt::SSLeay" "Crypt::SSLeay::CTX" "Crypt::SSLeay::Conn"
"Crypt::SSLeay::Err" "Crypt::SSLeay::MainContext" "Crypt::SSLeay::X509"
"Cwd" "DB" "DBD::DBM" "DBD::ExampleP" "DBD::File" "DBD::File::Developers"
"DBD::File::Roadmap" "DBD::Gofer" "DBD::Gofer::Policy::Base"
"DBD::Gofer::Policy::classic" "DBD::Gofer::Policy::pedantic"
"DBD::Gofer::Policy::rush" "DBD::Gofer::Transport::Base"
"DBD::Gofer::Transport::null" "DBD::Gofer::Transport::pipeone"
"DBD::Gofer::Transport::stream" "DBD::NullP" "DBD::Proxy" "DBD::Sponge"
"DBD::mysql" "DBD::mysql::GetInfo" "DBD::mysql::INSTALL" "DBI"
"DBI::Changes" "DBI::Const::GetInfo::ANSI" "DBI::Const::GetInfo::ODBC"
"DBI::Const::GetInfoReturn" "DBI::Const::GetInfoType" "DBI::DBD"
"DBI::DBD::Metadata" "DBI::DBD::SqlEngine" "DBI::FAQ" "DBI::Gofer::Execute"
"DBI::Gofer::Request" "DBI::Gofer::Response" "DBI::Gofer::Serializer::Base"
"DBI::Gofer::Serializer::DataDumper" "DBI::Gofer::Serializer::Storable"
"DBI::Gofer::Transport::Base" "DBI::Gofer::Transport::pipeone"
"DBI::Gofer::Transport::stream" "DBI::Profile" "DBI::ProfileData"
"DBI::ProfileDumper" "DBI::ProfileDumper::Apache" "DBI::ProfileSubs"
"DBI::ProxyServer" "DBI::PurePerl" "DBI::Roadmap" "DBI::SQL::Nano"
"DBI::Util::CacheMemory" "DBI::Util::_accessor" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper" "Date::Calc"
"Date::Calc::Object" "Date::Calc::PP" "Date::Calendar"
"Date::Calendar::Profiles" "Date::Calendar::Year" "Devel::Caller"
"Devel::DProf" "Devel::InnerPackage" "Devel::LexAlias" "Devel::PPPort"
"Devel::Peek" "Devel::SelfStubber" "Devel::Size" "Digest" "Digest::HMAC"
"Digest::HMAC_MD5" "Digest::HMAC_SHA1" "Digest::MD5" "Digest::SHA"
"Digest::SHA1" "Digest::base" "Digest::file" "DirHandle" "Dumpvalue"
"DynaLoader" "Encode" "Encode::Alias" "Encode::Byte" "Encode::CJKConstants"
"Encode::CN" "Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC"
"Encode::Encoder" "Encode::Encoding" "Encode::GSM0338" "Encode::Guess"
"Encode::JP" "Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR"
"Encode::KR::2022_KR" "Encode::MIME::Header"
"Encode::MIME::Header::ISO_2022_JP" "Encode::MIME::Name" "Encode::PerlIO"
"Encode::Supported" "Encode::Symbol" "Encode::TW" "Encode::Unicode"
"Encode::Unicode::UTF7" "English" "Env" "Errno" "Error" "Error::Simple"
"Exporter" "Exporter::Heavy" "ExtUtils::CBuilder"
"ExtUtils::CBuilder::Base" "ExtUtils::CBuilder::Platform::Unix"
"ExtUtils::CBuilder::Platform::VMS" "ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Install"
"ExtUtils::Installed" "ExtUtils::Liblist" "ExtUtils::Liblist::Kid"
"ExtUtils::MM" "ExtUtils::MM_AIX" "ExtUtils::MM_Any" "ExtUtils::MM_BeOS"
"ExtUtils::MM_Cygwin" "ExtUtils::MM_DOS" "ExtUtils::MM_Darwin"
"ExtUtils::MM_MacOS" "ExtUtils::MM_NW5" "ExtUtils::MM_OS2"
"ExtUtils::MM_QNX" "ExtUtils::MM_UWIN" "ExtUtils::MM_Unix"
"ExtUtils::MM_VMS" "ExtUtils::MM_VOS" "ExtUtils::MM_Win32"
"ExtUtils::MM_Win95" "ExtUtils::MY" "ExtUtils::MakeMaker"
"ExtUtils::MakeMaker::Config" "ExtUtils::MakeMaker::FAQ"
"ExtUtils::MakeMaker::Tutorial" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::ParseXS" "ExtUtils::testlib" "Fatal" "Fcntl" "File::BaseDir"
"File::Basename" "File::CheckTree" "File::Compare" "File::Copy"
"File::DesktopEntry" "File::DosGlob" "File::Find" "File::Find::Rule"
"File::Find::Rule::Extending" "File::Find::Rule::Procedural" "File::Glob"
"File::GlobMapper" "File::Listing" "File::MimeInfo"
"File::MimeInfo::Applications" "File::MimeInfo::Cookbook"
"File::MimeInfo::Magic" "File::MimeInfo::Rox" "File::Path" "File::Spec"
"File::Spec::Cygwin" "File::Spec::Epoc" "File::Spec::Functions"
"File::Spec::Mac" "File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS"
"File::Spec::Win32" "File::Temp" "File::stat" "FileCache" "FileHandle"
"Filter::Simple" "Filter::Util::Call" "FindBin" "Foomatic::DB"
"Foomatic::Defaults" "Foomatic::PPD" "Foomatic::UIElem" "GDBM_File"
"GSSAPI" "GSSAPI::OID" "GSSAPI::OID::Set" "GSSAPI::Status" "Getopt::Long"
"Getopt::Std" "Git" "Glib" "Glib::BookmarkFile" "Glib::Boxed"
"Glib::CodeGen" "Glib::Error" "Glib::Flags" "Glib::GenPod"
"Glib::Install::Files" "Glib::KeyFile" "Glib::Log" "Glib::MainLoop"
"Glib::Markup" "Glib::Object" "Glib::Object::Subclass"
"Glib::OptionContext" "Glib::OptionGroup" "Glib::Param::Boolean"
"Glib::Param::Double" "Glib::Param::Enum" "Glib::Param::Flags"
"Glib::Param::Int" "Glib::Param::Int64" "Glib::Param::String"
"Glib::Param::UInt" "Glib::Param::UInt64" "Glib::Param::Unichar"
"Glib::ParamSpec" "Glib::ParseXSDoc" "Glib::Signal" "Glib::Type"
"Glib::Utils" "Glib::index" "Glib::version" "Gtk2" "Gtk2::AboutDialog"
"Gtk2::AccelGroup" "Gtk2::AccelLabel" "Gtk2::AccelMap" "Gtk2::Accelerator"
"Gtk2::Action" "Gtk2::ActionGroup" "Gtk2::Adjustment" "Gtk2::Alignment"
"Gtk2::Arrow" "Gtk2::AspectFrame" "Gtk2::Assistant" "Gtk2::Bin" "Gtk2::Box"
"Gtk2::Buildable" "Gtk2::Buildable::ParseContext" "Gtk2::Builder"
"Gtk2::Button" "Gtk2::ButtonBox" "Gtk2::Calendar" "Gtk2::CellEditable"
"Gtk2::CellLayout" "Gtk2::CellLayout::DataFunc" "Gtk2::CellRenderer"
"Gtk2::CellRendererAccel" "Gtk2::CellRendererCombo"
"Gtk2::CellRendererPixbuf" "Gtk2::CellRendererProgress"
"Gtk2::CellRendererSpin" "Gtk2::CellRendererText"
"Gtk2::CellRendererToggle" "Gtk2::CellView" "Gtk2::CheckButton"
"Gtk2::CheckMenuItem" "Gtk2::Clipboard" "Gtk2::CodeGen" "Gtk2::ColorButton"
"Gtk2::ColorSelection" "Gtk2::ColorSelectionDialog" "Gtk2::Combo"
"Gtk2::ComboBox" "Gtk2::ComboBoxEntry" "Gtk2::Container" "Gtk2::Curve"
"Gtk2::Dialog" "Gtk2::Drag" "Gtk2::DrawingArea" "Gtk2::Editable"
"Gtk2::Entry" "Gtk2::EntryCompletion" "Gtk2::EventBox" "Gtk2::Expander"
"Gtk2::FileChooser" "Gtk2::FileChooserButton" "Gtk2::FileChooserDialog"
"Gtk2::FileChooserWidget" "Gtk2::FileFilter" "Gtk2::FileSelection"
"Gtk2::Fixed" "Gtk2::FontButton" "Gtk2::FontSelection"
"Gtk2::FontSelectionDialog" "Gtk2::Frame" "Gtk2::GC" "Gtk2::GammaCurve"
"Gtk2::Gdk" "Gtk2::Gdk::Atom" "Gtk2::Gdk::Bitmap"
"Gtk2::Gdk::Cairo::Context" "Gtk2::Gdk::Color" "Gtk2::Gdk::Colormap"
"Gtk2::Gdk::Cursor" "Gtk2::Gdk::Device" "Gtk2::Gdk::Display"
"Gtk2::Gdk::DisplayManager" "Gtk2::Gdk::DragContext" "Gtk2::Gdk::Drawable"
"Gtk2::Gdk::Event" "Gtk2::Gdk::Event::Button" "Gtk2::Gdk::Event::Client"
"Gtk2::Gdk::Event::Configure" "Gtk2::Gdk::Event::Crossing"
"Gtk2::Gdk::Event::DND" "Gtk2::Gdk::Event::Expose"
"Gtk2::Gdk::Event::Focus" "Gtk2::Gdk::Event::GrabBroken"
"Gtk2::Gdk::Event::Key" "Gtk2::Gdk::Event::Motion"
"Gtk2::Gdk::Event::NoExpose" "Gtk2::Gdk::Event::OwnerChange"
"Gtk2::Gdk::Event::Property" "Gtk2::Gdk::Event::Proximity"
"Gtk2::Gdk::Event::Scroll" "Gtk2::Gdk::Event::Selection"
"Gtk2::Gdk::Event::Setting" "Gtk2::Gdk::Event::Visibility"
"Gtk2::Gdk::Event::WindowState" "Gtk2::Gdk::GC" "Gtk2::Gdk::Geometry"
"Gtk2::Gdk::Input" "Gtk2::Gdk::Keymap" "Gtk2::Gdk::Keysyms"
"Gtk2::Gdk::Pango::AttrEmbossColor" "Gtk2::Gdk::Pango::AttrEmbossed"
"Gtk2::Gdk::Pango::AttrStipple" "Gtk2::Gdk::PangoRenderer"
"Gtk2::Gdk::Pixbuf" "Gtk2::Gdk::PixbufAnimation"
"Gtk2::Gdk::PixbufAnimationIter" "Gtk2::Gdk::PixbufFormat"
"Gtk2::Gdk::PixbufLoader" "Gtk2::Gdk::PixbufSimpleAnim" "Gtk2::Gdk::Pixmap"
"Gtk2::Gdk::Rectangle" "Gtk2::Gdk::Region" "Gtk2::Gdk::Rgb"
"Gtk2::Gdk::Screen" "Gtk2::Gdk::Selection" "Gtk2::Gdk::Threads"
"Gtk2::Gdk::Visual" "Gtk2::Gdk::Window" "Gtk2::Gdk::X11" "Gtk2::HBox"
"Gtk2::HButtonBox" "Gtk2::HPaned" "Gtk2::HRuler" "Gtk2::HScale"
"Gtk2::HScrollbar" "Gtk2::HSeparator" "Gtk2::HandleBox" "Gtk2::Helper"
"Gtk2::IMContext" "Gtk2::IMContextSimple" "Gtk2::IMMulticontext"
"Gtk2::IconFactory" "Gtk2::IconInfo" "Gtk2::IconSet" "Gtk2::IconSize"
"Gtk2::IconSource" "Gtk2::IconTheme" "Gtk2::IconView" "Gtk2::Image"
"Gtk2::ImageMenuItem" "Gtk2::InputDialog" "Gtk2::Install::Files"
"Gtk2::Invisible" "Gtk2::Item" "Gtk2::ItemFactory" "Gtk2::Label"
"Gtk2::Layout" "Gtk2::LinkButton" "Gtk2::List" "Gtk2::ListItem"
"Gtk2::ListStore" "Gtk2::Menu" "Gtk2::MenuBar" "Gtk2::MenuItem"
"Gtk2::MenuShell" "Gtk2::MenuToolButton" "Gtk2::MessageDialog" "Gtk2::Misc"
"Gtk2::Notebook" "Gtk2::Object" "Gtk2::OptionMenu" "Gtk2::PageSetup"
"Gtk2::Paned" "Gtk2::Pango" "Gtk2::Pango::AttrBackground"
"Gtk2::Pango::AttrColor" "Gtk2::Pango::AttrFallback"
"Gtk2::Pango::AttrFamily" "Gtk2::Pango::AttrFontDesc"
"Gtk2::Pango::AttrForeground" "Gtk2::Pango::AttrGravity"
"Gtk2::Pango::AttrGravityHint" "Gtk2::Pango::AttrInt"
"Gtk2::Pango::AttrIterator" "Gtk2::Pango::AttrLanguage"
"Gtk2::Pango::AttrLetterSpacing" "Gtk2::Pango::AttrList"
"Gtk2::Pango::AttrRise" "Gtk2::Pango::AttrScale" "Gtk2::Pango::AttrShape"
"Gtk2::Pango::AttrSize" "Gtk2::Pango::AttrStretch"
"Gtk2::Pango::AttrStrikethrough" "Gtk2::Pango::AttrStrikethroughColor"
"Gtk2::Pango::AttrString" "Gtk2::Pango::AttrStyle"
"Gtk2::Pango::AttrUnderline" "Gtk2::Pango::AttrUnderlineColor"
"Gtk2::Pango::AttrVariant" "Gtk2::Pango::AttrWeight"
"Gtk2::Pango::Attribute" "Gtk2::Pango::Cairo" "Gtk2::Pango::Cairo::Context"
"Gtk2::Pango::Cairo::Font" "Gtk2::Pango::Cairo::FontMap"
"Gtk2::Pango::Color" "Gtk2::Pango::Context" "Gtk2::Pango::Font"
"Gtk2::Pango::FontDescription" "Gtk2::Pango::FontFace"
"Gtk2::Pango::FontFamily" "Gtk2::Pango::FontMap" "Gtk2::Pango::FontMetrics"
"Gtk2::Pango::Fontset" "Gtk2::Pango::Gravity" "Gtk2::Pango::Language"
"Gtk2::Pango::Layout" "Gtk2::Pango::LayoutIter" "Gtk2::Pango::LayoutLine"
"Gtk2::Pango::Matrix" "Gtk2::Pango::Renderer" "Gtk2::Pango::Script"
"Gtk2::Pango::ScriptIter" "Gtk2::Pango::TabArray" "Gtk2::Pango::version"
"Gtk2::PaperSize" "Gtk2::Plug" "Gtk2::Print" "Gtk2::PrintContext"
"Gtk2::PrintOperation" "Gtk2::PrintOperationPreview" "Gtk2::PrintSettings"
"Gtk2::ProgressBar" "Gtk2::RadioAction" "Gtk2::RadioButton"
"Gtk2::RadioMenuItem" "Gtk2::RadioToolButton" "Gtk2::Range" "Gtk2::Rc"
"Gtk2::RcStyle" "Gtk2::RecentAction" "Gtk2::RecentChooser"
"Gtk2::RecentChooserDialog" "Gtk2::RecentChooserMenu"
"Gtk2::RecentChooserWidget" "Gtk2::RecentFilter" "Gtk2::RecentInfo"
"Gtk2::RecentManager" "Gtk2::Requisition" "Gtk2::Ruler" "Gtk2::Scale"
"Gtk2::ScaleButton" "Gtk2::Scrollbar" "Gtk2::ScrolledWindow"
"Gtk2::Selection" "Gtk2::SelectionData" "Gtk2::Separator"
"Gtk2::SeparatorMenuItem" "Gtk2::SeparatorToolItem" "Gtk2::SimpleList"
"Gtk2::SimpleMenu" "Gtk2::SizeGroup" "Gtk2::Socket" "Gtk2::SpinButton"
"Gtk2::StatusIcon" "Gtk2::Statusbar" "Gtk2::Stock" "Gtk2::Style"
"Gtk2::Table" "Gtk2::TargetEntry" "Gtk2::TargetList"
"Gtk2::TearoffMenuItem" "Gtk2::TestHelper" "Gtk2::TextAttributes"
"Gtk2::TextBuffer" "Gtk2::TextChildAnchor" "Gtk2::TextIter"
"Gtk2::TextMark" "Gtk2::TextTag" "Gtk2::TextTagTable" "Gtk2::TextView"
"Gtk2::ToggleAction" "Gtk2::ToggleButton" "Gtk2::ToggleToolButton"
"Gtk2::ToolButton" "Gtk2::ToolItem" "Gtk2::ToolShell" "Gtk2::Toolbar"
"Gtk2::Tooltip" "Gtk2::Tooltips" "Gtk2::TreeDragDest"
"Gtk2::TreeDragSource" "Gtk2::TreeIter" "Gtk2::TreeModel"
"Gtk2::TreeModelFilter" "Gtk2::TreeModelSort" "Gtk2::TreePath"
"Gtk2::TreeRowReference" "Gtk2::TreeSelection" "Gtk2::TreeSortable"
"Gtk2::TreeSortable::IterCompareFunc" "Gtk2::TreeStore" "Gtk2::TreeView"
"Gtk2::TreeViewColumn" "Gtk2::UIManager" "Gtk2::VBox" "Gtk2::VButtonBox"
"Gtk2::VPaned" "Gtk2::VRuler" "Gtk2::VScale" "Gtk2::VScrollbar"
"Gtk2::VSeparator" "Gtk2::Viewport" "Gtk2::VolumeButton" "Gtk2::Widget"
"Gtk2::Window" "Gtk2::WindowGroup" "Gtk2::api" "Gtk2::devel" "Gtk2::enums"
"Gtk2::index" "Gtk2::main" "Gtk2::version" "HTML::Entities" "HTML::Filter"
"HTML::Form" "HTML::HeadParser" "HTML::LinkExtor" "HTML::Parser"
"HTML::PullParser" "HTML::Tagset" "HTML::TokeParser" "HTTP::Config"
"HTTP::Cookies" "HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape"
"HTTP::Daemon" "HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth"
"HTTP::Headers::ETag" "HTTP::Headers::Util" "HTTP::Message"
"HTTP::Negotiate" "HTTP::Request" "HTTP::Request::Common" "HTTP::Response"
"HTTP::Status" "Hash::Util" "Hash::Util::FieldHash" "I18N::Collate"
"I18N::LangTags" "I18N::LangTags::Detect" "I18N::LangTags::List"
"I18N::Langinfo" "IO" "IO::AtomicFile" "IO::Compress::Adapter::Bzip2"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Bzip2"
"IO::Compress::Deflate" "IO::Compress::Gzip"
"IO::Compress::Gzip::Constants" "IO::Compress::RawDeflate"
"IO::Compress::Zip" "IO::Compress::Zip::Constants"
"IO::Compress::Zlib::Constants" "IO::Compress::Zlib::Extra" "IO::Dir"
"IO::File" "IO::Handle" "IO::InnerFile" "IO::Lines" "IO::Pipe" "IO::Poll"
"IO::Scalar" "IO::ScalarArray" "IO::Seekable" "IO::Select" "IO::Socket"
"IO::Socket::INET" "IO::Socket::SSL" "IO::Socket::UNIX" "IO::String"
"IO::Stringy" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Wrap" "IO::WrapTie" "IO::Zlib" "IPC::Msg"
"IPC::Open2" "IPC::Open3" "IPC::Semaphore" "IPC::SharedMem" "IPC::SysV"
"Image::Magick" "LWP" "LWP::Authen::Basic" "LWP::Authen::Digest"
"LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug" "LWP::DebugFile"
"LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol" "LWP::Protocol::GHTTP"
"LWP::Protocol::cpan" "LWP::Protocol::data" "LWP::Protocol::file"
"LWP::Protocol::ftp" "LWP::Protocol::gopher" "LWP::Protocol::http"
"LWP::Protocol::http10" "LWP::Protocol::https" "LWP::Protocol::https10"
"LWP::Protocol::ldap" "LWP::Protocol::ldaps" "LWP::Protocol::loopback"
"LWP::Protocol::mailto" "LWP::Protocol::nntp" "LWP::Protocol::nogo"
"LWP::RobotUA" "LWP::Simple" "LWP::UserAgent" "List::MoreUtils"
"List::Util" "List::Util::PP" "List::Util::XS" "Locale::Constants"
"Locale::Country" "Locale::Currency" "Locale::Language" "Locale::Maketext"
"Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::TPJ13" "Locale::Script" "Locale::gettext" "MIME::Base64"
"MIME::QuotedPrint" "Math::BigFloat" "Math::BigFloat::Trace" "Math::BigInt"
"Math::BigInt::Calc" "Math::BigInt::CalcEmu" "Math::BigInt::FastCalc"
"Math::BigInt::Trace" "Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::API"
"Module::Build::Authoring" "Module::Build::Base" "Module::Build::Bundling"
"Module::Build::Compat" "Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Info" "Module::Locate" "Module::Pluggable"
"Module::Pluggable::Object" "NDBM_File" "NEXT" "Net::Cmd" "Net::Config"
"Net::DNS" "Net::DNS::FAQ" "Net::DNS::Header" "Net::DNS::Packet"
"Net::DNS::Question" "Net::DNS::RR" "Net::DNS::RR::A" "Net::DNS::RR::AAAA"
"Net::DNS::RR::AFSDB" "Net::DNS::RR::APL" "Net::DNS::RR::APL::ApItem"
"Net::DNS::RR::CERT" "Net::DNS::RR::CNAME" "Net::DNS::RR::DNAME"
"Net::DNS::RR::EID" "Net::DNS::RR::HINFO" "Net::DNS::RR::IPSECKEY"
"Net::DNS::RR::ISDN" "Net::DNS::RR::LOC" "Net::DNS::RR::MB"
"Net::DNS::RR::MG" "Net::DNS::RR::MINFO" "Net::DNS::RR::MR"
"Net::DNS::RR::MX" "Net::DNS::RR::NAPTR" "Net::DNS::RR::NIMLOC"
"Net::DNS::RR::NS" "Net::DNS::RR::NSAP" "Net::DNS::RR::NULL"
"Net::DNS::RR::OPT" "Net::DNS::RR::PTR" "Net::DNS::RR::PX"
"Net::DNS::RR::RP" "Net::DNS::RR::RT" "Net::DNS::RR::SOA"
"Net::DNS::RR::SPF" "Net::DNS::RR::SRV" "Net::DNS::RR::SSHFP"
"Net::DNS::RR::TKEY" "Net::DNS::RR::TSIG" "Net::DNS::RR::TXT"
"Net::DNS::RR::Unknown" "Net::DNS::RR::X25" "Net::DNS::Resolver"
"Net::DNS::Resolver::Base" "Net::DNS::Resolver::Recurse"
"Net::DNS::Resolver::UNIX" "Net::DNS::Update" "Net::Domain" "Net::FTP"
"Net::FTP::A" "Net::FTP::E" "Net::FTP::I" "Net::FTP::L"
"Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods" "Net::HTTP::NB"
"Net::HTTPS" "Net::IP" "Net::LDAP" "Net::LDAP::ASN" "Net::LDAP::Bind"
"Net::LDAP::Constant" "Net::LDAP::Control"
"Net::LDAP::Control::EntryChange" "Net::LDAP::Control::ManageDsaIT"
"Net::LDAP::Control::Paged" "Net::LDAP::Control::PasswordPolicy"
"Net::LDAP::Control::PersistentSearch" "Net::LDAP::Control::PostRead"
"Net::LDAP::Control::PreRead" "Net::LDAP::Control::ProxyAuth"
"Net::LDAP::Control::Sort" "Net::LDAP::Control::SortResult"
"Net::LDAP::Control::SyncDone" "Net::LDAP::Control::SyncRequest"
"Net::LDAP::Control::SyncState" "Net::LDAP::Control::VLV"
"Net::LDAP::Control::VLVResponse" "Net::LDAP::DSML" "Net::LDAP::Entry"
"Net::LDAP::Examples" "Net::LDAP::Extension"
"Net::LDAP::Extension::Refresh" "Net::LDAP::Extension::SetPassword"
"Net::LDAP::Extension::WhoAmI" "Net::LDAP::Extra" "Net::LDAP::FAQ"
"Net::LDAP::Filter" "Net::LDAP::FilterMatch" "Net::LDAP::Intermediate"
"Net::LDAP::Intermediate::SyncInfo" "Net::LDAP::LDIF" "Net::LDAP::Message"
"Net::LDAP::RFC" "Net::LDAP::Reference" "Net::LDAP::RootDSE"
"Net::LDAP::Schema" "Net::LDAP::Search" "Net::LDAP::Security"
"Net::LDAP::Util" "Net::LDAPI" "Net::LDAPS" "Net::LibIDN" "Net::NNTP"
"Net::Netrc" "Net::POP3" "Net::Ping" "Net::SMTP" "Net::SNMP"
"Net::SNMP::Dispatcher" "Net::SNMP::Message" "Net::SNMP::MessageProcessing"
"Net::SNMP::PDU" "Net::SNMP::Security" "Net::SNMP::Security::Community"
"Net::SNMP::Security::USM" "Net::SNMP::Transport"
"Net::SNMP::Transport::IPv4" "Net::SNMP::Transport::IPv4::TCP"
"Net::SNMP::Transport::IPv4::UDP" "Net::SNMP::Transport::IPv6"
"Net::SNMP::Transport::IPv6::TCP" "Net::SNMP::Transport::IPv6::UDP"
"Net::SSL" "Net::SSLeay" "Net::SSLeay::Handle" "Net::Time" "Net::hostent"
"Net::libnetFAQ" "Net::netent" "Net::protoent" "Net::servent"
"Number::Compare" "O" "Ocsinventory::Agent"
"Ocsinventory::Agent::AccountConfig" "Ocsinventory::Agent::AccountInfo"
"Ocsinventory::Agent::Backend" "Ocsinventory::Agent::Backend::AccessLog"
"Ocsinventory::Agent::Backend::DeviceID"
"Ocsinventory::Agent::Backend::IpDiscover"
"Ocsinventory::Agent::Backend::IpDiscover::IpDiscover"
"Ocsinventory::Agent::Backend::IpDiscover::Nmap"
"Ocsinventory::Agent::Backend::OS::AIX"
"Ocsinventory::Agent::Backend::OS::AIX::CPU"
"Ocsinventory::Agent::Backend::OS::AIX::Controller"
"Ocsinventory::Agent::Backend::OS::AIX::Domains"
"Ocsinventory::Agent::Backend::OS::AIX::Drives"
"Ocsinventory::Agent::Backend::OS::AIX::Hardware"
"Ocsinventory::Agent::Backend::OS::AIX::IPv4"
"Ocsinventory::Agent::Backend::OS::AIX::Mem"
"Ocsinventory::Agent::Backend::OS::AIX::Memory"
"Ocsinventory::Agent::Backend::OS::AIX::Modems"
"Ocsinventory::Agent::Backend::OS::AIX::Networks"
"Ocsinventory::Agent::Backend::OS::AIX::Slots"
"Ocsinventory::Agent::Backend::OS::AIX::Software"
"Ocsinventory::Agent::Backend::OS::AIX::Sounds"
"Ocsinventory::Agent::Backend::OS::AIX::Storages"
"Ocsinventory::Agent::Backend::OS::AIX::Users"
"Ocsinventory::Agent::Backend::OS::AIX::Videos"
"Ocsinventory::Agent::Backend::OS::BSD"
"Ocsinventory::Agent::Backend::OS::BSD::Archs::Alpha"
"Ocsinventory::Agent::Backend::OS::BSD::Archs::I386"
"Ocsinventory::Agent::Backend::OS::BSD::Archs::Sgimips"
"Ocsinventory::Agent::Backend::OS::BSD::Archs::Sparc"
"Ocsinventory::Agent::Backend::OS::BSD::CPU"
"Ocsinventory::Agent::Backend::OS::BSD::Domains"
"Ocsinventory::Agent::Backend::OS::BSD::Drives"
"Ocsinventory::Agent::Backend::OS::BSD::IPv4"
"Ocsinventory::Agent::Backend::OS::BSD::Mem"
"Ocsinventory::Agent::Backend::OS::BSD::Networks"
"Ocsinventory::Agent::Backend::OS::BSD::Storages"
"Ocsinventory::Agent::Backend::OS::BSD::Sys"
"Ocsinventory::Agent::Backend::OS::BSD::Uptime"
"Ocsinventory::Agent::Backend::OS::Generic"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::Bios"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::Memory"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::Ports"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::Slots"
"Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::UUID"
"Ocsinventory::Agent::Backend::OS::Generic::Hostname"
"Ocsinventory::Agent::Backend::OS::Generic::Ipmi"
"Ocsinventory::Agent::Backend::OS::Generic::Lspci"
"Ocsinventory::Agent::Backend::OS::Generic::Lspci::Controllers"
"Ocsinventory::Agent::Backend::OS::Generic::Lspci::Modems"
"Ocsinventory::Agent::Backend::OS::Generic::Lspci::Sounds"
"Ocsinventory::Agent::Backend::OS::Generic::Lspci::Videos"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::BSDpkg"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::ByHand"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::Deb"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::Gentoo"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::Pacman"
"Ocsinventory::Agent::Backend::OS::Generic::Packaging::RPM"
"Ocsinventory::Agent::Backend::OS::Generic::Printers::Cups"
"Ocsinventory::Agent::Backend::OS::Generic::Processes"
"Ocsinventory::Agent::Backend::OS::Generic::Screen"
"Ocsinventory::Agent::Backend::OS::Generic::Users"
"Ocsinventory::Agent::Backend::OS::HPUX"
"Ocsinventory::Agent::Backend::OS::HPUX::Bios"
"Ocsinventory::Agent::Backend::OS::HPUX::CPU"
"Ocsinventory::Agent::Backend::OS::HPUX::Controller"
"Ocsinventory::Agent::Backend::OS::HPUX::Domains"
"Ocsinventory::Agent::Backend::OS::HPUX::Drives"
"Ocsinventory::Agent::Backend::OS::HPUX::IPv4"
"Ocsinventory::Agent::Backend::OS::HPUX::Mem"
"Ocsinventory::Agent::Backend::OS::HPUX::Memory"
"Ocsinventory::Agent::Backend::OS::HPUX::Networks"
"Ocsinventory::Agent::Backend::OS::HPUX::Slots"
"Ocsinventory::Agent::Backend::OS::HPUX::Software"
"Ocsinventory::Agent::Backend::OS::HPUX::Storages"
"Ocsinventory::Agent::Backend::OS::Linux"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::ARM"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::ARM::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::Alpha"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::Alpha::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::MIPS"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::MIPS::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::PowerPC"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::PowerPC::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::PowerPC::Various"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::SPARC"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::SPARC::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::i386"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::i386::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::m68k"
"Ocsinventory::Agent::Backend::OS::Linux::Archs::m68k::CPU"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::LSB"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::ArchLinux"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Debian"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Fedora"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Gentoo"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Knoppix"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Mandrake"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Mandriva"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Redhat"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Slackware"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::SuSE"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Trustix"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Ubuntu"
"Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::VmWare"
"Ocsinventory::Agent::Backend::OS::Linux::Domains"
"Ocsinventory::Agent::Backend::OS::Linux::Drives"
"Ocsinventory::Agent::Backend::OS::Linux::Mem"
"Ocsinventory::Agent::Backend::OS::Linux::Network::IPv4"
"Ocsinventory::Agent::Backend::OS::Linux::Network::Networks"
"Ocsinventory::Agent::Backend::OS::Linux::Sounds"
"Ocsinventory::Agent::Backend::OS::Linux::Storages"
"Ocsinventory::Agent::Backend::OS::Linux::Storages::3ware"
"Ocsinventory::Agent::Backend::OS::Linux::Storages::Adaptec"
"Ocsinventory::Agent::Backend::OS::Linux::Storages::HP"
"Ocsinventory::Agent::Backend::OS::Linux::Storages::Lsilogic"
"Ocsinventory::Agent::Backend::OS::Linux::Storages::ServeRaid"
"Ocsinventory::Agent::Backend::OS::Linux::Sys"
"Ocsinventory::Agent::Backend::OS::Linux::Uptime"
"Ocsinventory::Agent::Backend::OS::MacOS"
"Ocsinventory::Agent::Backend::OS::MacOS::Bios"
"Ocsinventory::Agent::Backend::OS::MacOS::CPU"
"Ocsinventory::Agent::Backend::OS::MacOS::Domains"
"Ocsinventory::Agent::Backend::OS::MacOS::Drives"
"Ocsinventory::Agent::Backend::OS::MacOS::Hostname"
"Ocsinventory::Agent::Backend::OS::MacOS::IPv4"
"Ocsinventory::Agent::Backend::OS::MacOS::Mem"
"Ocsinventory::Agent::Backend::OS::MacOS::Networks"
"Ocsinventory::Agent::Backend::OS::MacOS::Packages"
"Ocsinventory::Agent::Backend::OS::MacOS::Printers"
"Ocsinventory::Agent::Backend::OS::MacOS::Sound"
"Ocsinventory::Agent::Backend::OS::MacOS::Storages"
"Ocsinventory::Agent::Backend::OS::MacOS::Uptime"
"Ocsinventory::Agent::Backend::OS::MacOS::Video"
"Ocsinventory::Agent::Backend::OS::Solaris"
"Ocsinventory::Agent::Backend::OS::Solaris::Bios"
"Ocsinventory::Agent::Backend::OS::Solaris::CPU"
"Ocsinventory::Agent::Backend::OS::Solaris::Controllers"
"Ocsinventory::Agent::Backend::OS::Solaris::Domains"
"Ocsinventory::Agent::Backend::OS::Solaris::Drives"
"Ocsinventory::Agent::Backend::OS::Solaris::IPv4"
"Ocsinventory::Agent::Backend::OS::Solaris::Mem"
"Ocsinventory::Agent::Backend::OS::Solaris::Memory"
"Ocsinventory::Agent::Backend::OS::Solaris::Networks"
"Ocsinventory::Agent::Backend::OS::Solaris::Packages"
"Ocsinventory::Agent::Backend::OS::Solaris::Slots"
"Ocsinventory::Agent::Backend::OS::Solaris::Storages"
"Ocsinventory::Agent::Backend::OS::Solaris::Users"
"Ocsinventory::Agent::Backend::Virtualization::Libvirt"
"Ocsinventory::Agent::Backend::Virtualization::Parallels"
"Ocsinventory::Agent::Backend::Virtualization::Qemu"
"Ocsinventory::Agent::Backend::Virtualization::SolarisZones"
"Ocsinventory::Agent::Backend::Virtualization::VirtualBox"
"Ocsinventory::Agent::Backend::Virtualization::VmWareDesktop"
"Ocsinventory::Agent::Backend::Virtualization::VmWareESX"
"Ocsinventory::Agent::Backend::Virtualization::Vmsystem"
"Ocsinventory::Agent::Backend::Virtualization::Xen"
"Ocsinventory::Agent::Backend::Virtualization::Xen::XM"
"Ocsinventory::Agent::Common" "Ocsinventory::Agent::Config"
"Ocsinventory::Agent::Hooks" "Ocsinventory::Agent::Modules::Download"
"Ocsinventory::Agent::Modules::Example"
"Ocsinventory::Agent::Modules::Snmp"
"Ocsinventory::Agent::Modules::Snmp::11"
"Ocsinventory::Agent::Modules::Snmp::2620"
"Ocsinventory::Agent::Modules::Snmp::311"
"Ocsinventory::Agent::Modules::Snmp::3224"
"Ocsinventory::Agent::Modules::Snmp::3375"
"Ocsinventory::Agent::Modules::Snmp::641"
"Ocsinventory::Agent::Modules::Snmp::7244"
"Ocsinventory::Agent::Modules::Snmp::8072"
"Ocsinventory::Agent::Modules::Snmp::9"
"Ocsinventory::Agent::Modules::Snmp::Default"
"Ocsinventory::Agent::Modules::Snmp::Entity_Mib"
"Ocsinventory::Agent::Modules::Snmp::Host_Resources_Mib"
"Ocsinventory::Agent::Modules::Snmp::If_Mib"
"Ocsinventory::Agent::Modules::Snmp::Printer_Mib"
"Ocsinventory::Agent::Network" "Ocsinventory::Agent::XML::Inventory"
"Ocsinventory::Agent::XML::Prolog" "Ocsinventory::Agent::XML::Response"
"Ocsinventory::Agent::XML::Response::Inventory"
"Ocsinventory::Agent::XML::Response::Prolog"
"Ocsinventory::Agent::XML::SimpleMessage" "Ocsinventory::Compress"
"Ocsinventory::Logger" "Ocsinventory::LoggerBackend::File"
"Ocsinventory::LoggerBackend::Stderr" "Ocsinventory::LoggerBackend::Syslog"
"Opcode" "POSIX" "PPI" "PPI::Cache" "PPI::Document" "PPI::Document::File"
"PPI::Document::Fragment" "PPI::Document::Normalized" "PPI::Dumper"
"PPI::Element" "PPI::Exception" "PPI::Exception::ParserRejection"
"PPI::Exception::ParserTimeout" "PPI::Find" "PPI::Lexer" "PPI::Node"
"PPI::Normal" "PPI::Normal::Standard" "PPI::Statement"
"PPI::Statement::Break" "PPI::Statement::Compound" "PPI::Statement::Data"
"PPI::Statement::End" "PPI::Statement::Expression" "PPI::Statement::Given"
"PPI::Statement::Include" "PPI::Statement::Include::Perl6"
"PPI::Statement::Null" "PPI::Statement::Package"
"PPI::Statement::Scheduled" "PPI::Statement::Sub" "PPI::Statement::Unknown"
"PPI::Statement::UnmatchedBrace" "PPI::Statement::Variable"
"PPI::Statement::When" "PPI::Structure" "PPI::Structure::Block"
"PPI::Structure::Condition" "PPI::Structure::Constructor"
"PPI::Structure::For" "PPI::Structure::Given" "PPI::Structure::List"
"PPI::Structure::Subscript" "PPI::Structure::Unknown"
"PPI::Structure::When" "PPI::Token" "PPI::Token::ArrayIndex"
"PPI::Token::Attribute" "PPI::Token::BOM" "PPI::Token::Cast"
"PPI::Token::Comment" "PPI::Token::DashedWord" "PPI::Token::Data"
"PPI::Token::End" "PPI::Token::HereDoc" "PPI::Token::Label"
"PPI::Token::Magic" "PPI::Token::Number" "PPI::Token::Number::Binary"
"PPI::Token::Number::Exp" "PPI::Token::Number::Float"
"PPI::Token::Number::Hex" "PPI::Token::Number::Octal"
"PPI::Token::Number::Version" "PPI::Token::Operator" "PPI::Token::Pod"
"PPI::Token::Prototype" "PPI::Token::Quote" "PPI::Token::Quote::Double"
"PPI::Token::Quote::Interpolate" "PPI::Token::Quote::Literal"
"PPI::Token::Quote::Single" "PPI::Token::QuoteLike"
"PPI::Token::QuoteLike::Backtick" "PPI::Token::QuoteLike::Command"
"PPI::Token::QuoteLike::Readline" "PPI::Token::QuoteLike::Regexp"
"PPI::Token::QuoteLike::Words" "PPI::Token::Regexp"
"PPI::Token::Regexp::Match" "PPI::Token::Regexp::Substitute"
"PPI::Token::Regexp::Transliterate" "PPI::Token::Separator"
"PPI::Token::Structure" "PPI::Token::Symbol" "PPI::Token::Unknown"
"PPI::Token::Whitespace" "PPI::Token::Word" "PPI::Token::_QuoteEngine"
"PPI::Token::_QuoteEngine::Full" "PPI::Token::_QuoteEngine::Simple"
"PPI::Tokenizer" "PPI::Transform" "PPI::Transform::UpdateCopyright"
"PPI::Util" "PPI::XSAccessor" "Package::Constants" "PadWalker"
"Params::Util" "Parse::ALex" "Parse::CLex" "Parse::ExuberantCTags"
"Parse::Lex" "Parse::LexEvent" "Parse::Template" "Parse::Token"
"Parse::Token-t" "Parse::Trace" "Parse::YYLex" "Parse::Yapp"
"Parse::Yapp::Driver" "Parse::Yapp::Grammar" "Parse::Yapp::Lalr"
"Parse::Yapp::Options" "Parse::Yapp::Output" "Parse::Yapp::Parse"
"Perl::Tags" "Perl::Tags::Naive::Lib" "Perl::Tags::Naive::Spiffy"
"Perl::Tags::PPI" "PerlIO" "PerlIO::encoding" "PerlIO::scalar"
"PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Escapes"
"Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX"
"Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToChecker"
"Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff" "Pod::Perldoc::ToPod"
"Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText" "Pod::Perldoc::ToTk"
"Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Plainer" "Pod::Select"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "Proc::Daemon"
"Proc::Killall" "Proc::Killfam" "Proc::PID::File" "Proc::ProcessTable"
"Proc::ProcessTable::Process" "Roadmap" "SDBM_File" "Safe" "Scalar::Util"
"Scalar::Util::PP" "Search::Dict" "SelectSaver" "SelfLoader" "Sepia"
"Sepia::CPAN" "Sepia::Debug" "Sepia::ReadLine" "Sepia::Xref" "Shell"
"Socket" "Socket6" "Storable" "Switch" "Symbol" "Sys::Hostname"
"Sys::Syslog" "TAP::Base" "TAP::Formatter::Base" "TAP::Formatter::Color"
"TAP::Formatter::Console" "TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Object" "TAP::Parser" "TAP::Parser::Aggregator"
"TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::Source::Perl" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer" "TASKS"
"Term::ANSIColor" "Term::Cap" "Term::Complete" "Term::ReadLine" "Test"
"Test::Builder" "Test::Builder::IO::Scalar" "Test::Builder::Module"
"Test::Builder::Tester" "Test::Builder::Tester::Color" "Test::Harness"
"Test::More" "Test::Simple" "Test::Tutorial" "Text::Abbrev"
"Text::Balanced" "Text::Glob" "Text::ParseWords" "Text::Soundex"
"Text::Tabs" "Text::Wrap" "Thread" "Thread::Queue" "Thread::Semaphore"
"Tie::Array" "Tie::File" "Tie::Handle" "Tie::Hash"
"Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash" "Tie::Scalar"
"Tie::StdHandle" "Tie::SubstrHash" "Time::HiRes" "Time::Local"
"Time::gmtime" "Time::localtime" "Time::tm" "UNIVERSAL" "URI" "URI::Escape"
"URI::Heuristic" "URI::IRI" "URI::QueryParam" "URI::Split" "URI::URL"
"URI::WithBase" "URI::_foreign" "URI::_generic" "URI::_idna" "URI::_ldap"
"URI::_login" "URI::_punycode" "URI::_query" "URI::_segment" "URI::_server"
"URI::_userpass" "URI::data" "URI::file" "URI::file::Base" "URI::file::FAT"
"URI::file::Mac" "URI::file::OS2" "URI::file::QNX" "URI::file::Unix"
"URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http" "URI::https"
"URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms" "URI::news"
"URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu"
"URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270"
"URI::urn" "URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Normalize" "Unicode::UCD" "User::grent" "User::pwent"
"WWW::RobotRules" "WWW::RobotRules::AnyDBM_File" "XML::LibXML"
"XML::LibXML::Attr" "XML::LibXML::Boolean" "XML::LibXML::CDATASection"
"XML::LibXML::Comment" "XML::LibXML::Common" "XML::LibXML::DOM"
"XML::LibXML::Document" "XML::LibXML::DocumentFragment" "XML::LibXML::Dtd"
"XML::LibXML::Element" "XML::LibXML::ErrNo" "XML::LibXML::Error"
"XML::LibXML::InputCallback" "XML::LibXML::Literal"
"XML::LibXML::Namespace" "XML::LibXML::Node" "XML::LibXML::NodeList"
"XML::LibXML::Number" "XML::LibXML::PI" "XML::LibXML::Parser"
"XML::LibXML::Pattern" "XML::LibXML::Reader" "XML::LibXML::RegExp"
"XML::LibXML::RelaxNG" "XML::LibXML::SAX" "XML::LibXML::SAX::Builder"
"XML::LibXML::SAX::Generator" "XML::LibXML::SAX::Parser"
"XML::LibXML::Schema" "XML::LibXML::Text" "XML::LibXML::XPathContext"
"XML::LibXML::XPathExpression" "XML::NamespaceSupport" "XML::Parser"
"XML::Parser::Expat" "XML::Parser::Style::Debug"
"XML::Parser::Style::Objects" "XML::Parser::Style::Stream"
"XML::Parser::Style::Subs" "XML::Parser::Style::Tree" "XML::SAX"
"XML::SAX::Base" "XML::SAX::DocumentLocator" "XML::SAX::Exception"
"XML::SAX::Intro" "XML::SAX::ParserFactory" "XML::SAX::PurePerl"
"XML::SAX::PurePerl::DTDDecls" "XML::SAX::PurePerl::DebugHandler"
"XML::SAX::PurePerl::DocType" "XML::SAX::PurePerl::EncodingDetect"
"XML::SAX::PurePerl::Exception" "XML::SAX::PurePerl::NoUnicodeExt"
"XML::SAX::PurePerl::Productions" "XML::SAX::PurePerl::Reader"
"XML::SAX::PurePerl::Reader::NoUnicodeExt"
"XML::SAX::PurePerl::Reader::Stream" "XML::SAX::PurePerl::Reader::String"
"XML::SAX::PurePerl::Reader::URI" "XML::SAX::PurePerl::Reader::UnicodeExt"
"XML::SAX::PurePerl::UnicodeExt" "XML::SAX::PurePerl::XMLDecl"
"XML::Simple" "XML::Simple::FAQ" "XML::Twig" "XML::Twig::XPath" "XSLoader"
"a2p" "attributes" "autodie" "autodie::exception"
"autodie::exception::system" "autodie::hints" "autouse" "base" "bigint"
"bignum" "bigrat" "blib" "bytes" "charnames" "constant" "deprecate"
"diagnostics" "encoding" "encoding::warnings" "feature" "fields" "filetest"
"if" "inc::latest" "inc::latest::private" "integer" "less" "lib" "locale"
"lwpcook" "lwptut" "mro" "open.pod" "ops" "overload" "overload::numbers"
"overloading" "perl" "perl5004delta" "perl5005delta" "perl5100delta"
"perl5101delta" "perl5110delta" "perl5111delta" "perl5112delta"
"perl5113delta" "perl5114delta" "perl5115delta" "perl5120delta"
"perl5121delta" "perl5122delta" "perl5123delta" "perl5124delta"
"perl561delta" "perl56delta" "perl570delta" "perl571delta" "perl572delta"
"perl573delta" "perl581delta" "perl582delta" "perl583delta" "perl584delta"
"perl585delta" "perl586delta" "perl587delta" "perl588delta" "perl589delta"
"perl58delta" "perl590delta" "perl591delta" "perl592delta" "perl593delta"
"perl594delta" "perl595delta" "perlaix" "perlamiga" "perlapi" "perlapio"
"perlapollo" "perlartistic" "perlbeos" "perlbook" "perlboot" "perlbot"
"perlbs2000" "perlcall" "perlce" "perlcheat" "perlclib" "perlcn"
"perlcommunity" "perlcompile" "perlcygwin" "perldata" "perldbmfilter"
"perldebguts" "perldebtut" "perldebug" "perldelta" "perldgux" "perldiag"
"perldoc" "perldos" "perldsc" "perlebcdic" "perlembed" "perlepoc" "perlfaq"
"perlfaq1" "perlfaq2" "perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6"
"perlfaq7" "perlfaq8" "perlfaq9" "perlfilter" "perlfork" "perlform"
"perlfreebsd" "perlfunc" "perlglossary" "perlgpl" "perlguts" "perlhack"
"perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern" "perlintro"
"perliol" "perlipc" "perlirix" "perljp" "perlko" "perllexwarn" "perllinux"
"perllocal" "perllocale" "perllol" "perlmacos" "perlmacosx" "perlmod"
"perlmodinstall" "perlmodlib" "perlmodstyle" "perlmpeix" "perlmroapi"
"perlnetware" "perlnewmod" "perlnumber" "perlobj" "perlop" "perlopenbsd"
"perlopentut" "perlos2" "perlos390" "perlos400" "perlpacktut" "perlperf"
"perlplan9" "perlpod" "perlpodspec" "perlpolicy" "perlport" "perlpragma"
"perlqnx" "perlre" "perlreapi" "perlrebackslash" "perlrecharclass"
"perlref" "perlreftut" "perlreguts" "perlrepository" "perlrequick"
"perlreref" "perlretut" "perlriscos" "perlrun" "perlsec" "perlsolaris"
"perlstyle" "perlsub" "perlsymbian" "perlsyn" "perlthrtut" "perltie"
"perltoc" "perltodo" "perltooc" "perltoot" "perltrap" "perltru64" "perltw"
"perlunicode" "perlunifaq" "perluniintro" "perluniprops" "perlunitut"
"perlutil" "perluts" "perlvar" "perlvmesa" "perlvms" "perlvos" "perlwin32"
"perlxs" "perlxstut" "re" "sigtrap" "sort.pod" "strict" "subs" "threads"
"threads::shared" "utf8" "vars" "vmsish" "warnings" "warnings::register"))
